name: Publish
on: [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: bun run build

      - name: npm CI
        run: npm ci

      - name: Publish
        run: npm publish --provinence
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
