name: Test
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun lint

      - name: Check Formatting
        run: bun lint:format

      - name: Build
        run: bun run build
